name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ok-nick/setup-aftman@v0.4.2
      - run: aftman install
      - run: stylua --check src examples
      - run: selene src examples/basic/src
      - run: rojo build example.project.json --output bundle-framework-example.rbxlx
      - run: rojo build package.project.json --output bundle-framework.rbxm